security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    # Configuration du hachage automatique des mots de passe pour les utilisateurs authentifiés par mot de passe

    providers:
        # Configuration du fournisseur d'utilisateurs pour charger les utilisateurs de l'application
        # via une entité utilisateur avec une propriété "email"
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            # Pare-feu pour l'environnement de développement
            # Désactive la sécurité pour certaines URL utilisées en développement

        main:
            lazy: true
            provider: app_user_provider
            # Pare-feu principal pour l'authentification utilisateur
            # Utilise le fournisseur "app_user_provider" pour charger les utilisateurs
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: false
                # Configuration de l'authentification via un formulaire de connexion
                # avec désactivation de la protection CSRF pour cette démo

            logout:
                path: app_logout
                target: home
                # Configuration du processus de déconnexion utilisateur

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Contrôle d'accès restreignant l'accès à l'URL commençant par "/admin" aux utilisateurs avec le rôle "ROLE_ADMIN"


when@test:
    security:
        password_hashers:
              Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
              algorithm: auto
              cost: 4 # Lowest possible value for bcrypt
              time_cost: 3 # Lowest possible value for argon
              memory_cost: 10 # Lowest possible value for argon
